import sys
sys.path.insert(0, r"c:\Users\seany\Documents\All Codes\Data Science Study Path")
from _inserter import insert_sections

# ─── PLOTLY ───────────────────────────────────────────────────────────────────
PLOTLY_PATH = r"c:\Users\seany\Documents\All Codes\Data Science Study Path\gen_plotly.py"
PLOTLY_MARKER = "]  # end SECTIONS"

PLOTLY_SECTIONS = '''    {
        "title": "14. Dash App Fundamentals",
        "examples": [
            {
                "label": "Basic Dash app structure (printed pattern)",
                "code": "# Dash apps run as web servers — this shows the code pattern\napp_code = '''\nfrom dash import Dash, dcc, html\nfrom dash.dependencies import Input, Output\nimport plotly.express as px\n\napp = Dash(__name__)\napp.layout = html.Div([\n    html.H1(\"Dashboard\"),\n    dcc.Dropdown(id='metric', options=['Revenue','Users','Churn'], value='Revenue'),\n    dcc.Graph(id='chart'),\n])\n\n@app.callback(Output('chart','figure'), Input('metric','value'))\ndef update(metric):\n    import numpy as np, pandas as pd\n    df = pd.DataFrame({'date': pd.date_range('2024-01-01', periods=30),\n                        metric: np.cumsum(np.random.randn(30)) + 100})\n    return px.line(df, x='date', y=metric, title=f'{metric} over Time')\n\nif __name__ == '__main__':\n    app.run_server(debug=True)\n'''\nprint('Dash app structure:')\nprint(app_code)"
            },
            {
                "label": "Plotly figure for Dash callback",
                "code": "import plotly.graph_objects as go\nimport plotly.express as px\nimport numpy as np\nimport pandas as pd\n\n# Simulate what a Dash callback would return for given filter values\ndef make_dashboard_fig(category='All', start_date='2024-01-01'):\n    np.random.seed(42)\n    dates = pd.date_range(start_date, periods=90, freq='D')\n    cats = ['Electronics','Apparel','Food']\n    dfs = [pd.DataFrame({'date':dates,'revenue':np.random.exponential(1000,90),'category':c}) for c in cats]\n    df = pd.concat(dfs)\n    if category != 'All':\n        df = df[df.category == category]\n    fig = px.area(df.groupby(['date','category'])['revenue'].sum().reset_index(),\n                  x='date', y='revenue', color='category',\n                  title=f'Revenue — {category}', template='plotly_white')\n    fig.update_layout(hovermode='x unified', height=400)\n    return fig\n\nfig = make_dashboard_fig('Electronics')\nfig.write_html('dash_callback_fig.html')\nprint(f'Dashboard figure saved — traces: {len(fig.data)}')"
            },
            {
                "label": "Dash DataTable structure",
                "code": "# DataTable pattern for interactive data grids\ntable_code = '''\nfrom dash import dash_table\nimport pandas as pd\n\ndf = pd.read_csv(\"data.csv\")\nlayout = dash_table.DataTable(\n    data=df.to_dict(\"records\"),\n    columns=[{\"name\": c, \"id\": c} for c in df.columns],\n    filter_action=\"native\",\n    sort_action=\"native\",\n    page_size=10,\n    export_format=\"csv\",\n    style_data_conditional=[{\n        \"if\": {\"filter_query\": \"{revenue} > 1000\"},\n        \"backgroundColor\": \"#d4edda\",\n    }],\n)\n'''\nprint('DataTable pattern:')\nprint(table_code)\nprint('Key features: filter_action, sort_action, export_format, conditional styling')"
            },
            {
                "label": "Multi-page Dash routing pattern",
                "code": "# Multi-page Dash pattern (Dash 2.x file-based routing)\npages_code = '''\n# pages/home.py\nimport dash\ndash.register_page(__name__, path=\"/\")\nlayout = html.Div([html.H2(\"Home\"), ...])\n\n# pages/analytics.py\ndash.register_page(__name__, path=\"/analytics\")\nlayout = html.Div([dcc.Graph(figure=create_fig()), ...])\n\n# app.py\napp = Dash(__name__, use_pages=True)\napp.layout = html.Div([\n    html.Nav([dcc.Link(\"Home\",href=\"/\"), dcc.Link(\"Analytics\",href=\"/analytics\")]),\n    dash.page_container  # renders current page\n])\n'''\nprint('Multi-page Dash pattern:')\nprint(pages_code)\nprint('\\nEach page: dash.register_page(__name__, path=\"/route\")')\nprint('app.py: use_pages=True + dash.page_container')"
            }
        ],
        "rw_scenario": "You're building an internal analytics dashboard where users can filter by date range and category, with charts updating automatically and a data table for export.",
        "rw_code": "import plotly.graph_objects as go\nimport plotly.express as px\nimport numpy as np\nimport pandas as pd\n\n# Simulate multi-trace dashboard figure (what callback returns)\nnp.random.seed(42)\ndates = pd.date_range('2024-01-01', periods=180, freq='D')\ncats = ['Electronics','Apparel','Food']\nfig = go.Figure()\nfor cat in cats:\n    rev = np.random.exponential(1000, 180).cumsum()\n    fig.add_trace(go.Scatter(x=dates, y=rev, name=cat, mode='lines', fill='tonexty' if cat != 'Electronics' else None))\nfig.update_layout(title='Revenue Dashboard Preview', xaxis_title='Date', yaxis_title='Revenue ($)',\n                  template='plotly_white', hovermode='x unified',\n                  legend=dict(orientation='h', y=-0.2))\nfig.write_html('dashboard_preview.html')\nprint(f'Dashboard saved — {len(fig.data)} traces, {len(dates)} days')",
        "practice": {
            "title": "Filter Callback Simulation",
            "desc": "Write a function make_fig(year, continent) that filters the gapminder dataset and returns a scatter plot of GDP vs life expectancy. Call it with 3 different inputs and save each as HTML.",
            "starter": "import plotly.express as px\n\ngap = px.data.gapminder()\n\ndef make_fig(year, continent):\n    # TODO: filter by year and continent (or 'All')\n    # TODO: return px.scatter with size='pop', color='country', log_x=True\n    pass\n\nfor year, cont in [(1952, 'Asia'), (2007, 'Europe'), (2007, 'All')]:\n    fig = make_fig(year, cont)\n    if fig: fig.write_html(f'gap_{year}_{cont}.html')"
        }
    },
    {
        "title": "15. Map Visualizations",
        "examples": [
            {
                "label": "Choropleth world map",
                "code": "import plotly.express as px\n\ndf = px.data.gapminder().query(\"year == 2007\")\nfig = px.choropleth(df, locations='iso_alpha', color='gdpPercap',\n                    hover_name='country', color_continuous_scale='Viridis',\n                    range_color=[0, 50000], title='GDP per Capita (2007)',\n                    labels={'gdpPercap': 'GDP per Capita'})\nfig.update_layout(geo=dict(showframe=False, showcoastlines=True))\nfig.write_html('choropleth_world.html')\nprint(f'Choropleth saved — {len(df)} countries')"
            },
            {
                "label": "Scatter geo map (USA)",
                "code": "import plotly.express as px\nimport pandas as pd\nimport numpy as np\n\nnp.random.seed(42)\ndf = pd.DataFrame({'lat': np.random.uniform(25, 50, 80), 'lon': np.random.uniform(-125, -65, 80),\n                   'city': [f'City_{i}' for i in range(80)],\n                   'sales': np.random.exponential(500, 80),\n                   'category': np.random.choice(['A','B','C'], 80)})\nfig = px.scatter_geo(df, lat='lat', lon='lon', size='sales', color='category',\n                     hover_name='city', scope='usa', title='Sales Distribution USA', size_max=20)\nfig.write_html('scatter_map.html')\nprint(f'Scatter geo saved — {len(df)} points')"
            },
            {
                "label": "Animated choropleth over time",
                "code": "import plotly.express as px\n\ndf = px.data.gapminder()\nfig = px.choropleth(df, locations='iso_alpha', color='lifeExp',\n                    hover_name='country', animation_frame='year',\n                    color_continuous_scale='RdYlGn', range_color=[30, 90],\n                    title='Life Expectancy Over Time')\nfig.update_layout(geo=dict(showframe=False))\nfig.write_html('choropleth_animated.html')\nprint(f'Animated choropleth — {df.year.nunique()} frames')"
            },
            {
                "label": "Density mapbox heatmap",
                "code": "import plotly.express as px\nimport pandas as pd\nimport numpy as np\n\nnp.random.seed(42)\ndf = pd.DataFrame({'lat': np.random.normal(40.7128, 0.05, 400),\n                   'lon': np.random.normal(-74.006, 0.05, 400),\n                   'intensity': np.random.exponential(1, 400)})\nfig = px.density_mapbox(df, lat='lat', lon='lon', z='intensity', radius=15,\n                         center=dict(lat=40.7128, lon=-74.006), zoom=10,\n                         mapbox_style='open-street-map',\n                         title='Event Density (NYC Area)', color_continuous_scale='Inferno')\nfig.write_html('density_map.html')\nprint(f'Density map saved — {len(df)} events')"
            }
        ],
        "rw_scenario": "You need to visualize global customer distribution with bubble sizes representing revenue and colors representing satisfaction, animated across 4 quarters.",
        "rw_code": "import plotly.express as px\nimport pandas as pd\nimport numpy as np\n\nnp.random.seed(42)\ncountry_coords = {'USA':(37.09,-95.71),'DEU':(51.16,10.45),'GBR':(55.37,-3.44),\n                  'JPN':(36.20,138.25),'BRA':(-14.23,-51.92),'IND':(20.59,78.96),'CHN':(35.86,104.19)}\nrows = []\nfor q in ['Q1','Q2','Q3','Q4']:\n    for country,(lat,lon) in country_coords.items():\n        rows.append({'quarter':q,'country':country,'lat':lat+np.random.randn()*0.5,\n                     'lon':lon+np.random.randn()*0.5,'revenue':np.random.exponential(500000),\n                     'satisfaction':np.random.uniform(3,5)})\ndf = pd.DataFrame(rows)\nfig = px.scatter_geo(df, lat='lat', lon='lon', size='revenue', color='satisfaction',\n                     hover_name='country', animation_frame='quarter',\n                     color_continuous_scale='RdYlGn', range_color=[3,5], size_max=40,\n                     title='Global Customer Revenue & Satisfaction')\nfig.write_html('global_map.html')\nprint(f'Global map saved — {len(df)} records, {df.quarter.nunique()} frames')",
        "practice": {
            "title": "US State Choropleth",
            "desc": "Create a choropleth map of US states using locationmode='USA-states'. Assign random 'performance_score' values (0-100) to each state abbreviation. Add hover data showing state and score.",
            "starter": "import plotly.express as px\nimport pandas as pd\nimport numpy as np\n\nstates = ['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA',\n          'KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',\n          'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT',\n          'VA','WA','WV','WI','WY']\nnp.random.seed(42)\ndf = pd.DataFrame({'state': states, 'score': np.random.uniform(40, 100, len(states))})\n# TODO: px.choropleth with locationmode='USA-states', locations='state', color='score'\n# TODO: scope='usa', color_continuous_scale='RdYlGn'\n# TODO: save to 'us_choropleth.html'"
        }
    },
    {
        "title": "16. 3D Plots & Surface Visualizations",
        "examples": [
            {
                "label": "3D surface with contour projections",
                "code": "import plotly.graph_objects as go\nimport numpy as np\n\nx = np.linspace(-3, 3, 60)\ny = np.linspace(-3, 3, 60)\nX, Y = np.meshgrid(x, y)\nZ = np.sin(np.sqrt(X**2 + Y**2))\n\nfig = go.Figure(go.Surface(x=X, y=Y, z=Z, colorscale='Viridis',\n                             contours={'z':{'show':True,'start':-1,'end':1,'size':0.25}}))\nfig.update_layout(title='3D Surface: sin(sqrt(x\u00b2+y\u00b2))',\n                  scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z',\n                             camera=dict(eye=dict(x=1.5, y=-1.5, z=1.2))),\n                  width=700, height=500)\nfig.write_html('surface_3d.html')\nprint('3D surface saved')"
            },
            {
                "label": "3D scatter with color encoding",
                "code": "import plotly.express as px\nimport numpy as np\n\nnp.random.seed(42)\nn = 300\nx = np.random.randn(n); y = np.random.randn(n)\nz = x**2 + y**2 + np.random.randn(n) * 0.5\ncats = np.where(z < 2, 'Inner', np.where(z < 5, 'Middle', 'Outer'))\nfig = px.scatter_3d(x=x, y=y, z=z, color=cats, symbol=cats,\n                    color_discrete_sequence=px.colors.qualitative.Set1,\n                    title='3D Scatter by Distance from Origin')\nfig.update_traces(marker=dict(size=4, opacity=0.7))\nfig.write_html('scatter_3d.html')\nprint(f'3D scatter saved — {n} points, {len(set(cats))} clusters')"
            },
            {
                "label": "3D spiral trajectory",
                "code": "import plotly.graph_objects as go\nimport numpy as np\n\nt = np.linspace(0, 8*np.pi, 500)\nx = np.cos(t) * np.exp(-t/20)\ny = np.sin(t) * np.exp(-t/20)\nz = t / (4*np.pi)\n\nfig = go.Figure()\nfig.add_trace(go.Scatter3d(x=x, y=y, z=z, mode='lines',\n                            line=dict(color=t, colorscale='Plasma', width=4), name='Trajectory'))\nfig.add_trace(go.Scatter3d(x=[x[0]], y=[y[0]], z=[z[0]], mode='markers',\n                            marker=dict(size=8, color='green'), name='Start'))\nfig.add_trace(go.Scatter3d(x=[x[-1]], y=[y[-1]], z=[z[-1]], mode='markers',\n                            marker=dict(size=8, color='red'), name='End'))\nfig.update_layout(title='3D Spiral Trajectory',\n                  scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Height'))\nfig.write_html('trajectory_3d.html')\nprint('3D trajectory saved')"
            },
            {
                "label": "Loss landscape with gradient descent path",
                "code": "import plotly.graph_objects as go\nimport numpy as np\n\nx = y = np.linspace(-3, 3, 60)\nX, Y = np.meshgrid(x, y)\nZ = (np.sin(X*2)*np.cos(Y*2)*0.5 + (X**2+Y**2)*0.1 +\n     np.exp(-((X-1)**2+(Y-1)**2))*(-1.5))\nZ = (Z - Z.min()) / (Z.max() - Z.min()) * 3\n\n# Simple gradient descent path\npx_path, py_path, pz_path = [2.5], [-2.5], [Z[0,-1]]\nlr = 0.08\nfor _ in range(60):\n    ix = np.argmin(np.abs(x - px_path[-1]))\n    iy = np.argmin(np.abs(y - py_path[-1]))\n    gx = (Z[iy, min(ix+1,59)] - Z[iy, max(ix-1,0)]) / 2\n    gy = (Z[min(iy+1,59), ix] - Z[max(iy-1,0), ix]) / 2\n    nx, ny = np.clip(px_path[-1] - lr*gx, -3, 3), np.clip(py_path[-1] - lr*gy, -3, 3)\n    px_path.append(float(nx)); py_path.append(float(ny))\n    pz_path.append(float(Z[np.argmin(np.abs(y-ny)), np.argmin(np.abs(x-nx))]))\n\nfig = go.Figure([go.Surface(x=X, y=Y, z=Z, colorscale='RdYlGn_r', opacity=0.85),\n                  go.Scatter3d(x=px_path, y=py_path, z=pz_path, mode='lines+markers',\n                               line=dict(color='blue', width=5), marker=dict(size=3),\n                               name='GD Path')])\nfig.update_layout(title='Loss Landscape + Gradient Descent', width=750, height=550)\nfig.write_html('loss_landscape.html')\nprint(f'Loss landscape saved — final loss: {pz_path[-1]:.3f}')"
            }
        ],
        "rw_scenario": "You need to visualize a machine learning model's loss surface in 3D to understand convergence behavior and identify local minima during hyperparameter search.",
        "rw_code": "import plotly.graph_objects as go\nimport plotly.express as px\nimport numpy as np\nfrom sklearn.datasets import make_classification\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.preprocessing import StandardScaler\n\n# Create loss surface for 2 hyperparameters (C and l1_ratio)\nnp.random.seed(42)\nX, y = make_classification(n_samples=300, n_features=5, random_state=42)\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\nC_vals = np.logspace(-2, 2, 20)\nlambda_vals = np.linspace(0.01, 0.99, 20)\nCV, LV = np.meshgrid(C_vals, lambda_vals)\nZ = np.zeros_like(CV)\n\nfor i in range(len(lambda_vals)):\n    for j in range(len(C_vals)):\n        try:\n            lr = LogisticRegression(C=C_vals[j], solver='saga', penalty='elasticnet',\n                                    l1_ratio=lambda_vals[i], max_iter=200, random_state=42)\n            lr.fit(X_scaled, y)\n            Z[i,j] = 1 - lr.score(X_scaled, y)  # training error as proxy\n        except:\n            Z[i,j] = 0.5\n\nbest_idx = np.unravel_index(Z.argmin(), Z.shape)\nfig = go.Figure([go.Surface(x=np.log10(CV), y=LV, z=Z, colorscale='RdYlGn_r',\n                              colorbar=dict(title='Train Error')),\n                  go.Scatter3d(x=[np.log10(C_vals[best_idx[1]])], y=[lambda_vals[best_idx[0]]], z=[Z.min()],\n                               mode='markers', marker=dict(size=10, color='gold', symbol='diamond'),\n                               name='Best params')])\nfig.update_layout(title='Elastic Net Hyperparameter Loss Surface',\n                  scene=dict(xaxis_title='log10(C)', yaxis_title='l1_ratio', zaxis_title='Train Error'))\nfig.write_html('hyperparam_surface.html')\nprint(f'Best: C={C_vals[best_idx[1]]:.3f}, l1_ratio={lambda_vals[best_idx[0]]:.3f}, error={Z.min():.4f}')",
        "practice": {
            "title": "3D Scatter by Cluster",
            "desc": "Generate 3 Gaussian clusters in 3D (centers at (0,0,0), (3,3,0), (0,3,3)). Create a 3D scatter plot with each cluster in a different color/symbol. Add a semi-transparent bounding sphere. Save as HTML.",
            "starter": "import plotly.graph_objects as go\nimport numpy as np\n\nnp.random.seed(42)\nclusters = [(0,0,0), (3,3,0), (0,3,3)]\ncolors = ['blue','red','green']\nfig = go.Figure()\nfor i, (cx,cy,cz) in enumerate(clusters):\n    n = 50\n    x = np.random.randn(n)+cx; y = np.random.randn(n)+cy; z = np.random.randn(n)+cz\n    # TODO: add Scatter3d trace for this cluster\n    pass\n# TODO: update_layout with title and axis labels\n# TODO: fig.write_html('clusters_3d.html')"
        }
    },
'''

insert_sections(PLOTLY_PATH, PLOTLY_MARKER, PLOTLY_SECTIONS)

# ─── SQL ──────────────────────────────────────────────────────────────────────
SQL_PATH = r"c:\Users\seany\Documents\All Codes\Data Science Study Path\gen_sql.py"
SQL_MARKER = "]  # end SECTIONS"

SQL_SECTIONS = '''    {
        "title": "14. Query Optimization & Indexing",
        "examples": [
            {
                "label": "EXPLAIN QUERY PLAN to analyze queries",
                "code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER,\n                         amount REAL, status TEXT, order_date TEXT);\n    INSERT INTO orders SELECT value, (value%100)+1, RANDOM()*1000,\n        CASE value%3 WHEN 0 THEN 'pending' WHEN 1 THEN 'completed' ELSE 'cancelled' END,\n        date('2024-01-01', '+'||(value%365)||' days')\n    FROM generate_series(1, 10000);\n''')\nplan = conn.execute('''\n    EXPLAIN QUERY PLAN\n    SELECT customer_id, COUNT(*), AVG(amount)\n    FROM orders WHERE status='completed'\n    GROUP BY customer_id ORDER BY AVG(amount) DESC\n''').fetchall()\nprint('Query plan (no index):')\nfor row in plan: print(' ', row)\nconn.close()"
            },
            {
                "label": "Index creation and speedup measurement",
                "code": "import sqlite3, time\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE sales (id INTEGER PRIMARY KEY, region TEXT, amount REAL, sale_date TEXT);\n    INSERT INTO sales SELECT value, CASE value%4 WHEN 0 THEN 'North' WHEN 1 THEN 'South'\n        WHEN 2 THEN 'East' ELSE 'West' END, RANDOM()*1000,\n        date('2024-01-01', '+'||(value%365)||' days')\n    FROM generate_series(1, 100000);\n''')\nquery = \"SELECT region, AVG(amount) FROM sales WHERE sale_date > '2024-06-01' GROUP BY region\"\nt0 = time.time(); conn.execute(query).fetchall(); t_slow = time.time() - t0\nconn.execute('CREATE INDEX idx_date ON sales(sale_date)')\nt0 = time.time(); conn.execute(query).fetchall(); t_fast = time.time() - t0\nprint(f'Without index: {t_slow*1000:.1f}ms')\nprint(f'With index:    {t_fast*1000:.1f}ms')\nprint(f'Speedup: {t_slow/t_fast:.1f}x')\nconn.close()"
            },
            {
                "label": "Avoiding N+1 with JOINs",
                "code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, dept_id INTEGER, salary REAL);\n    CREATE TABLE departments (id INTEGER PRIMARY KEY, name TEXT, budget REAL);\n    INSERT INTO departments VALUES (1,'Engineering',500000),(2,'Sales',300000),(3,'HR',200000);\n    INSERT INTO employees SELECT v, 'Emp '||v, (v%3)+1, 50000+RANDOM()*50000\n    FROM generate_series(1,30) v;\n''')\nprint('=== N+1 (avoid this) ===')\nfor eid,name,dept_id in conn.execute('SELECT id,name,dept_id FROM employees LIMIT 3').fetchall():\n    dept = conn.execute('SELECT name FROM departments WHERE id=?',(dept_id,)).fetchone()\n    print(f'  {name} -> {dept[0]}')\nprint('=== Single JOIN (preferred) ===')\nfor row in conn.execute('SELECT e.name, d.name dept, e.salary FROM employees e JOIN departments d ON e.dept_id=d.id LIMIT 3').fetchall():\n    print(f'  {row[0]} | {row[1]} | ${row[2]:,.0f}')\nconn.close()"
            },
            {
                "label": "CTE vs subquery — readability comparison",
                "code": "import sqlite3, pandas as pd\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE transactions (id INTEGER PRIMARY KEY, user_id INTEGER, amount REAL,\n                               type TEXT, ts TEXT);\n    INSERT INTO transactions SELECT v, (v%50)+1, RANDOM()*500,\n        CASE v%3 WHEN 0 THEN 'purchase' WHEN 1 THEN 'refund' ELSE 'fee' END,\n        date('2024-01-01','+'||(v%300)||' days') FROM generate_series(1,1000) v;\n''')\ncte_query = '''\n    WITH purchase_summary AS (\n        SELECT user_id, SUM(amount) total, COUNT(*) cnt\n        FROM transactions WHERE type='purchase' GROUP BY user_id\n    ), avg_thresh AS (\n        SELECT AVG(amount)*5 threshold FROM transactions WHERE type='purchase'\n    )\n    SELECT ps.user_id, ROUND(ps.total,2) total, ps.cnt\n    FROM purchase_summary ps, avg_thresh at WHERE ps.total > at.threshold\n    ORDER BY ps.total DESC LIMIT 5\n'''\ndf = pd.read_sql(cte_query, conn)\nprint('Top buyers via CTE:')\nprint(df.to_string(index=False))\nconn.close()"
            }
        ],
        "rw_scenario": "Your analytics query on 500K rows takes 45 seconds. You need to use EXPLAIN to identify bottlenecks and add the right composite indexes to get it under 1 second.",
        "rw_code": "import sqlite3, time, pandas as pd\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE events (id INTEGER PRIMARY KEY, user_id INTEGER, event_type TEXT,\n                         product_id INTEGER, revenue REAL, ts TEXT);\n    INSERT INTO events SELECT v, (v%10000)+1,\n        CASE v%5 WHEN 0 THEN 'view' WHEN 1 THEN 'click' WHEN 2 THEN 'add_cart'\n                 WHEN 3 THEN 'purchase' ELSE 'abandon' END,\n        (v%1000)+1, CASE v%5 WHEN 3 THEN RANDOM()*200 ELSE 0 END,\n        datetime('2024-01-01','+'||(v%365)||' days','+'||(v%86400)||' seconds')\n    FROM generate_series(1,200000) v;\n''')\nslowq = \"SELECT user_id, COUNT(DISTINCT product_id) prods, SUM(revenue) rev FROM events WHERE ts >= '2024-06-01' AND product_id BETWEEN 100 AND 200 GROUP BY user_id HAVING rev > 0 ORDER BY rev DESC LIMIT 20\"\nt0 = time.time(); conn.execute(slowq).fetchall(); t1 = time.time()-t0\nconn.execute('CREATE INDEX idx_ts ON events(ts)')\nconn.execute('CREATE INDEX idx_compound ON events(ts, product_id, user_id)')\nt0 = time.time(); res = conn.execute(slowq).fetchall(); t2 = time.time()-t0\nprint(f'Without index: {t1*1000:.0f}ms | With indexes: {t2*1000:.0f}ms | Speedup: {t1/max(t2,0.0001):.1f}x')\nif res: print(f'Top user: {res[0][0]} — Revenue: ${res[0][2]:.2f}')\nconn.close()",
        "practice": {
            "title": "Index Advisor",
            "desc": "Create a 100K-row orders table. Measure query time for a filter on customer_id WITHOUT index. Add the index. Re-run and print speedup. Use EXPLAIN QUERY PLAN before and after to show the difference.",
            "starter": "import sqlite3, time\n\nconn = sqlite3.connect(':memory:')\n# TODO: create orders table with 100K rows\n# TODO: measure slow query time (filter on customer_id)\n# TODO: EXPLAIN QUERY PLAN before index\n# TODO: CREATE INDEX\n# TODO: measure fast query time\n# TODO: print speedup\nconn.close()"
        }
    },
    {
        "title": "15. Pivoting & Unpivoting Data",
        "examples": [
            {
                "label": "Pivot with CASE WHEN (manual pivot)",
                "code": "import sqlite3, pandas as pd\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE sales (year INTEGER, quarter TEXT, region TEXT, revenue REAL);\n    INSERT INTO sales VALUES\n        (2024,'Q1','North',120000),(2024,'Q2','North',135000),(2024,'Q3','North',118000),(2024,'Q4','North',145000),\n        (2024,'Q1','South',98000),(2024,'Q2','South',105000),(2024,'Q3','South',112000),(2024,'Q4','South',125000);\n''')\ndf = pd.read_sql('''\n    SELECT region,\n        SUM(CASE WHEN quarter='Q1' THEN revenue ELSE 0 END) Q1,\n        SUM(CASE WHEN quarter='Q2' THEN revenue ELSE 0 END) Q2,\n        SUM(CASE WHEN quarter='Q3' THEN revenue ELSE 0 END) Q3,\n        SUM(CASE WHEN quarter='Q4' THEN revenue ELSE 0 END) Q4,\n        SUM(revenue) Total\n    FROM sales GROUP BY region ORDER BY Total DESC\n''', conn)\nprint(df.to_string(index=False))\nconn.close()"
            },
            {
                "label": "Unpivot (wide to long) with UNION ALL",
                "code": "import sqlite3, pandas as pd\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE server_metrics (server TEXT, cpu_pct REAL, mem_pct REAL, disk_pct REAL, net_pct REAL);\n    INSERT INTO server_metrics VALUES ('web-01',72.5,65.2,45.0,30.1),('web-02',55.0,70.8,52.3,28.7),('db-01',88.2,91.5,78.4,15.2);\n''')\ndf = pd.read_sql('''\n    SELECT server,'CPU' metric, cpu_pct value FROM server_metrics\n    UNION ALL SELECT server,'Memory',mem_pct FROM server_metrics\n    UNION ALL SELECT server,'Disk',disk_pct FROM server_metrics\n    UNION ALL SELECT server,'Network',net_pct FROM server_metrics\n    ORDER BY server, metric\n''', conn)\nprint(df.to_string(index=False))\nconn.close()"
            },
            {
                "label": "Dynamic pivot with Python",
                "code": "import sqlite3, pandas as pd\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE survey (respondent INTEGER, question TEXT, score INTEGER);\n    INSERT INTO survey VALUES (1,'Q1',4),(1,'Q2',5),(1,'Q3',3),(1,'Q4',4),\n        (2,'Q1',3),(2,'Q2',4),(2,'Q3',5),(2,'Q4',2),(3,'Q1',5),(3,'Q2',5),(3,'Q3',4),(3,'Q4',5);\n''')\nquestions = [r[0] for r in conn.execute('SELECT DISTINCT question FROM survey ORDER BY question')]\ncases = ',\\n    '.join(f\"MAX(CASE WHEN question='{q}' THEN score END) AS {q}\" for q in questions)\ndf = pd.read_sql(f'SELECT respondent, {cases}, ROUND(AVG(score),2) avg_score FROM survey GROUP BY respondent ORDER BY avg_score DESC', conn)\nprint(df.to_string(index=False))\nconn.close()"
            },
            {
                "label": "Cross-tabulation with percentages",
                "code": "import sqlite3, pandas as pd\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE feedback (category TEXT, sentiment TEXT, count INTEGER);\n    INSERT INTO feedback VALUES ('Product','Positive',450),('Product','Neutral',120),('Product','Negative',80),\n        ('Service','Positive',380),('Service','Neutral',95),('Service','Negative',125),\n        ('Price','Positive',200),('Price','Neutral',180),('Price','Negative',220);\n''')\ndf = pd.read_sql('''\n    SELECT category,\n        SUM(CASE WHEN sentiment='Positive' THEN count ELSE 0 END) positive,\n        SUM(CASE WHEN sentiment='Neutral' THEN count ELSE 0 END) neutral,\n        SUM(CASE WHEN sentiment='Negative' THEN count ELSE 0 END) negative,\n        SUM(count) total,\n        ROUND(100.0*SUM(CASE WHEN sentiment='Positive' THEN count ELSE 0 END)/SUM(count),1) pct_pos\n    FROM feedback GROUP BY category ORDER BY pct_pos DESC\n''', conn)\nprint(df.to_string(index=False))\nconn.close()"
            }
        ],
        "rw_scenario": "Your reporting team needs monthly revenue by 5 product categories as a pivot table. Categories come from data (dynamic), so you must build the query programmatically.",
        "rw_code": "import sqlite3, pandas as pd, numpy as np\n\nconn = sqlite3.connect(':memory:')\nnp.random.seed(42)\ncats = ['Electronics','Apparel','Food','Sports','Books']\nmonths = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']\nrows = [(c,m,int(np.random.exponential(50000))) for c in cats for m in months]\nconn.executescript('CREATE TABLE monthly_sales (category TEXT, month TEXT, revenue INTEGER);')\nconn.executemany('INSERT INTO monthly_sales VALUES (?,?,?)', rows)\nmonth_order = {m:i for i,m in enumerate(months)}\nmonth_list = sorted([r[0] for r in conn.execute('SELECT DISTINCT month FROM monthly_sales')], key=lambda m: month_order.get(m,99))\ncases = ',\\n    '.join(f\"SUM(CASE WHEN month='{m}' THEN revenue ELSE 0 END) [{m}]\" for m in month_list)\nquery = f'SELECT category, {cases}, SUM(revenue) [Annual Total], ROUND(AVG(revenue)) [Monthly Avg] FROM monthly_sales GROUP BY category ORDER BY [Annual Total] DESC'\ndf = pd.read_sql(query, conn)\nfor col in month_list + ['Annual Total','Monthly Avg']:\n    df[col] = df[col].apply(lambda x: f'${x:,.0f}')\nprint('Monthly Revenue Pivot Table:')\nprint(df.to_string(index=False))\nconn.close()",
        "practice": {
            "title": "Dynamic Sales Pivot",
            "desc": "Create a sales table with 5 sales reps and 4 quarters. Write code that: (1) gets distinct quarters from the DB, (2) builds a pivot query dynamically with CASE WHEN, (3) displays results as a DataFrame.",
            "starter": "import sqlite3, pandas as pd, numpy as np\n\nconn = sqlite3.connect(':memory:')\nnp.random.seed(42)\nreps = ['Alice','Bob','Carol','Dave','Eve']\nquarters = ['Q1','Q2','Q3','Q4']\nrows = [(r,q,int(np.random.exponential(80000))) for r in reps for q in quarters]\nconn.executescript('CREATE TABLE rep_sales (rep TEXT, quarter TEXT, revenue INTEGER);')\nconn.executemany('INSERT INTO rep_sales VALUES (?,?,?)', rows)\n# TODO: get distinct quarters\n# TODO: build CASE WHEN pivot query\n# TODO: read to DataFrame and print\nconn.close()"
        }
    },
    {
        "title": "16. Triggers & Database Automation",
        "examples": [
            {
                "label": "Audit log trigger on UPDATE",
                "code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL);\n    CREATE TABLE price_audit (log_id INTEGER PRIMARY KEY AUTOINCREMENT,\n        product_id INTEGER, old_price REAL, new_price REAL, changed_at DATETIME DEFAULT CURRENT_TIMESTAMP);\n    INSERT INTO products VALUES (1,'Widget',9.99),(2,'Gadget',24.99);\n    CREATE TRIGGER log_price_change AFTER UPDATE OF price ON products\n    BEGIN INSERT INTO price_audit(product_id,old_price,new_price) VALUES (NEW.id,OLD.price,NEW.price); END;\n''')\nconn.execute('UPDATE products SET price=12.99 WHERE id=1')\nconn.execute('UPDATE products SET price=29.99 WHERE id=2')\nfor row in conn.execute('SELECT * FROM price_audit').fetchall():\n    print(f'Product {row[1]}: ${row[2]} -> ${row[3]} at {row[4]}')\nconn.close()"
            },
            {
                "label": "Business rule trigger (prevent negative stock)",
                "code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE inventory (product_id INTEGER PRIMARY KEY, quantity INTEGER CHECK(quantity >= 0));\n    CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER, qty INTEGER);\n    INSERT INTO inventory VALUES (1,100),(2,5);\n    CREATE TRIGGER decrement_stock AFTER INSERT ON orders\n    BEGIN UPDATE inventory SET quantity=quantity-NEW.qty WHERE product_id=NEW.product_id; END;\n''')\nconn.execute('INSERT INTO orders(product_id,qty) VALUES(1,30)')\nprint('After ordering 30 units of product 1:')\nfor row in conn.execute('SELECT * FROM inventory').fetchall():\n    print(f'  Product {row[0]}: {row[1]} units')\ntry:\n    conn.execute('INSERT INTO orders(product_id,qty) VALUES(2,10)')  # Will fail: 5-10 < 0\nexcept Exception as e:\n    print(f'Order failed (CHECK constraint): {type(e).__name__}')\nconn.close()"
            },
            {
                "label": "Stored procedure simulation with Python",
                "code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE accounts (id INTEGER PRIMARY KEY, name TEXT, balance REAL);\n    CREATE TABLE transfers (id INTEGER PRIMARY KEY AUTOINCREMENT,\n        from_acct INTEGER, to_acct INTEGER, amount REAL, ts DATETIME DEFAULT CURRENT_TIMESTAMP);\n    INSERT INTO accounts VALUES (1,'Alice',5000),(2,'Bob',1500),(3,'Carol',3200);\n''')\n\ndef transfer_funds(conn, from_id, to_id, amount):\n    bal = conn.execute('SELECT balance FROM accounts WHERE id=?',(from_id,)).fetchone()\n    if not bal or bal[0] < amount:\n        print(f'  FAILED: insufficient funds ({bal[0] if bal else 0:.2f} < {amount:.2f})')\n        return\n    conn.execute('BEGIN')\n    conn.execute('UPDATE accounts SET balance=balance-? WHERE id=?',(amount,from_id))\n    conn.execute('UPDATE accounts SET balance=balance+? WHERE id=?',(amount,to_id))\n    conn.execute('INSERT INTO transfers(from_acct,to_acct,amount) VALUES(?,?,?)',(from_id,to_id,amount))\n    conn.execute('COMMIT')\n    print(f'  OK: ${amount:.2f} from {from_id} to {to_id}')\n\ntransfer_funds(conn,1,2,500)\ntransfer_funds(conn,2,3,3000)  # should fail\nfor row in conn.execute('SELECT id,name,balance FROM accounts').fetchall():\n    print(f'{row[1]}: ${row[2]:.2f}')\nconn.close()"
            },
            {
                "label": "INSTEAD OF trigger on updatable view",
                "code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, salary REAL, dept TEXT);\n    INSERT INTO employees VALUES (1,'Alice',75000,'Eng'),(2,'Bob',68000,'Sales');\n    CREATE VIEW emp_view AS SELECT id, name, salary, dept FROM employees;\n    CREATE TRIGGER update_via_view INSTEAD OF UPDATE OF salary ON emp_view\n    BEGIN UPDATE employees SET salary=NEW.salary WHERE id=OLD.id; END;\n''')\nconn.execute(\"UPDATE emp_view SET salary=90000 WHERE name='Alice'\")\nfor row in conn.execute('SELECT name, salary FROM employees').fetchall():\n    print(f'{row[0]}: ${row[1]:,.0f}')\nconn.close()"
            }
        ],
        "rw_scenario": "Your e-commerce database needs: (1) audit logs for all price changes, (2) auto inventory deduction on orders, (3) transactional safety for payments.",
        "rw_code": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.executescript('''\n    CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL, stock INTEGER);\n    CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER, qty INTEGER,\n                         total REAL, status TEXT DEFAULT 'pending');\n    CREATE TABLE price_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER,\n                              old_price REAL, new_price REAL, pct_change REAL,\n                              ts DATETIME DEFAULT CURRENT_TIMESTAMP);\n    CREATE TABLE stock_alerts (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER,\n                               stock INTEGER, alert TEXT, ts DATETIME DEFAULT CURRENT_TIMESTAMP);\n    INSERT INTO products VALUES (1,'Laptop',999.99,50),(2,'Mouse',29.99,200),(3,'Keyboard',79.99,8);\n    CREATE TRIGGER audit_price AFTER UPDATE OF price ON products\n    BEGIN INSERT INTO price_audit(product_id,old_price,new_price,pct_change)\n        VALUES(NEW.id,OLD.price,NEW.price,ROUND(100.0*(NEW.price-OLD.price)/OLD.price,2)); END;\n    CREATE TRIGGER low_stock AFTER UPDATE OF stock ON products WHEN NEW.stock < 10\n    BEGIN INSERT INTO stock_alerts(product_id,stock,alert)\n        VALUES(NEW.id,NEW.stock,CASE WHEN NEW.stock=0 THEN 'OUT_OF_STOCK' ELSE 'LOW_STOCK' END); END;\n''')\n\ndef place_order(conn, product_id, qty):\n    row = conn.execute('SELECT stock,price,name FROM products WHERE id=?',(product_id,)).fetchone()\n    if not row or row[0] < qty:\n        print(f'  FAILED: only {row[0] if row else 0} in stock')\n        return\n    stock,price,name = row\n    conn.execute('INSERT INTO orders(product_id,qty,total,status) VALUES(?,?,?,\"completed\")',(product_id,qty,price*qty))\n    conn.execute('UPDATE products SET stock=stock-? WHERE id=?',(qty,product_id))\n    print(f'  Ordered {qty}x {name} = ${price*qty:.2f}')\n\nconn.execute('UPDATE products SET price=899.99 WHERE id=1')\nconn.execute('UPDATE products SET price=34.99 WHERE id=2')\nplace_order(conn,1,5)\nplace_order(conn,3,5)  # will trigger low stock alert (8-5=3)\nplace_order(conn,2,250)  # will fail\nprint('\\nPrice Audit:')\nfor r in conn.execute('SELECT product_id,old_price,new_price,pct_change FROM price_audit').fetchall():\n    print(f'  Product {r[0]}: ${r[1]} -> ${r[2]} ({r[3]:+.1f}%)')\nprint('\\nStock Alerts:')\nfor r in conn.execute('SELECT product_id,stock,alert FROM stock_alerts').fetchall():\n    print(f'  Product {r[0]}: {r[2]} ({r[1]} units)')\nconn.close()",
        "practice": {
            "title": "Banking Triggers",
            "desc": "Create accounts and transactions tables. Add triggers that: (1) log all withdrawals > $1000 to a large_withdrawals table, (2) prevent negative balances via CHECK. Test with 5 transactions including one that should fail.",
            "starter": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\n# TODO: CREATE TABLE accounts (id, name, balance)\n# TODO: CREATE TABLE large_withdrawals (id AUTOINCREMENT, account_id, amount, ts)\n# TODO: CREATE TRIGGER log_large_withdrawal AFTER INSERT ON transactions WHEN amount > 1000\n# TODO: CREATE TABLE transactions with CHECK balance >= 0 enforced via trigger\n# TODO: test with deposits and withdrawals\nconn.close()"
        }
    },
'''

insert_sections(SQL_PATH, SQL_MARKER, SQL_SECTIONS)
